//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:03:12 PM GMT 
//


package Sandbox.ZipExtractor;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="icap-repositories">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="icap-repository" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="licensing">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="module" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="expiry-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="activation-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="partner-image-url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="partner-link-url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="list-size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="site-guid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="log-file-request-date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="product-version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "icapRepositories",
    "licensing",
    "any"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(name = "icap-repositories", required = true)
    protected Configuration.IcapRepositories icapRepositories;
    @XmlElement(required = true)
    protected Configuration.Licensing licensing;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the icapRepositories property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.IcapRepositories }
     *     
     */
    public Configuration.IcapRepositories getIcapRepositories() {
        return icapRepositories;
    }

    /**
     * Sets the value of the icapRepositories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.IcapRepositories }
     *     
     */
    public void setIcapRepositories(Configuration.IcapRepositories value) {
        this.icapRepositories = value;
    }

    /**
     * Gets the value of the licensing property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Licensing }
     *     
     */
    public Configuration.Licensing getLicensing() {
        return licensing;
    }

    /**
     * Sets the value of the licensing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Licensing }
     *     
     */
    public void setLicensing(Configuration.Licensing value) {
        this.licensing = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="icap-repository" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "icapRepository"
    })
    public static class IcapRepositories {

        @XmlElement(name = "icap-repository", required = true)
        protected List<Configuration.IcapRepositories.IcapRepository> icapRepository;

        /**
         * Gets the value of the icapRepository property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the icapRepository property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIcapRepository().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.IcapRepositories.IcapRepository }
         * 
         * 
         */
        public List<Configuration.IcapRepositories.IcapRepository> getIcapRepository() {
            if (icapRepository == null) {
                icapRepository = new ArrayList<Configuration.IcapRepositories.IcapRepository>();
            }
            return this.icapRepository;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="url" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="identity" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class IcapRepository {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "url", required = true)
            protected String url;
            @XmlAttribute(name = "identity")
            protected String identity;
            @XmlAttribute(name = "password")
            protected String password;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the identity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentity() {
                return identity;
            }

            /**
             * Sets the value of the identity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentity(String value) {
                this.identity = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="module" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="expiry-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="activation-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="partner-image-url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="partner-link-url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="list-size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="site-guid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="log-file-request-date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="product-version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "module"
    })
    public static class Licensing {

        @XmlElement(required = true)
        protected List<Configuration.Licensing.Module> module;
        @XmlAttribute(name = "list-size", required = true)
        protected int listSize;
        @XmlAttribute(name = "site-guid", required = true)
        protected String siteGuid;
        @XmlAttribute(name = "log-file-request-date")
        protected String logFileRequestDate;
        @XmlAttribute(name = "product-version", required = true)
        protected String productVersion;

        /**
         * Gets the value of the module property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the module property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Configuration.Licensing.Module }
         * 
         * 
         */
        public List<Configuration.Licensing.Module> getModule() {
            if (module == null) {
                module = new ArrayList<Configuration.Licensing.Module>();
            }
            return this.module;
        }

        /**
         * Gets the value of the listSize property.
         * 
         */
        public int getListSize() {
            return listSize;
        }

        /**
         * Sets the value of the listSize property.
         * 
         */
        public void setListSize(int value) {
            this.listSize = value;
        }

        /**
         * Gets the value of the siteGuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSiteGuid() {
            return siteGuid;
        }

        /**
         * Sets the value of the siteGuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSiteGuid(String value) {
            this.siteGuid = value;
        }

        /**
         * Gets the value of the logFileRequestDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogFileRequestDate() {
            return logFileRequestDate;
        }

        /**
         * Sets the value of the logFileRequestDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogFileRequestDate(String value) {
            this.logFileRequestDate = value;
        }

        /**
         * Gets the value of the productVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductVersion() {
            return productVersion;
        }

        /**
         * Sets the value of the productVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductVersion(String value) {
            this.productVersion = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="expiry-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="activation-date" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="partner-image-url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="partner-link-url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Module {

            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "expiry-date", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar expiryDate;
            @XmlAttribute(name = "activation-date", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar activationDate;
            @XmlAttribute(name = "partner-image-url")
            protected String partnerImageUrl;
            @XmlAttribute(name = "partner-link-url")
            protected String partnerLinkUrl;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the expiryDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getExpiryDate() {
                return expiryDate;
            }

            /**
             * Sets the value of the expiryDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setExpiryDate(XMLGregorianCalendar value) {
                this.expiryDate = value;
            }

            /**
             * Gets the value of the activationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getActivationDate() {
                return activationDate;
            }

            /**
             * Sets the value of the activationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setActivationDate(XMLGregorianCalendar value) {
                this.activationDate = value;
            }

            /**
             * Gets the value of the partnerImageUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPartnerImageUrl() {
                return partnerImageUrl;
            }

            /**
             * Sets the value of the partnerImageUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPartnerImageUrl(String value) {
                this.partnerImageUrl = value;
            }

            /**
             * Gets the value of the partnerLinkUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPartnerLinkUrl() {
                return partnerLinkUrl;
            }

            /**
             * Sets the value of the partnerLinkUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPartnerLinkUrl(String value) {
                this.partnerLinkUrl = value;
            }

        }

    }

}
