//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:03:12 PM GMT 
//


package Sandbox.ZipExtractor;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="geodata" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ts" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="simd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="wimd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="imd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="crts" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="ward" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="postcode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geodata"
})
@XmlRootElement(name = "geomapping")
public class Geomapping {

    @XmlElement(required = true)
    protected List<Geomapping.Geodata> geodata;

    /**
     * Gets the value of the geodata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geodata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeodata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Geomapping.Geodata }
     * 
     * 
     */
    public List<Geomapping.Geodata> getGeodata() {
        if (geodata == null) {
            geodata = new ArrayList<Geomapping.Geodata>();
        }
        return this.geodata;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ts" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="simd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="wimd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="imd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="crts" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="ward" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="postcode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ts",
        "simd",
        "wimd",
        "imd",
        "crts",
        "ward"
    })
    public static class Geodata {

        @XmlElement(required = true, nillable = true)
        protected BigDecimal ts;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal simd;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal wimd;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal imd;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal crts;
        @XmlElement(required = true)
        protected String ward;
        @XmlAttribute(name = "postcode", required = true)
        protected String postcode;

        /**
         * Gets the value of the ts property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTs() {
            return ts;
        }

        /**
         * Sets the value of the ts property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTs(BigDecimal value) {
            this.ts = value;
        }

        /**
         * Gets the value of the simd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSimd() {
            return simd;
        }

        /**
         * Sets the value of the simd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSimd(BigDecimal value) {
            this.simd = value;
        }

        /**
         * Gets the value of the wimd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getWimd() {
            return wimd;
        }

        /**
         * Sets the value of the wimd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setWimd(BigDecimal value) {
            this.wimd = value;
        }

        /**
         * Gets the value of the imd property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getImd() {
            return imd;
        }

        /**
         * Sets the value of the imd property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setImd(BigDecimal value) {
            this.imd = value;
        }

        /**
         * Gets the value of the crts property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCrts() {
            return crts;
        }

        /**
         * Sets the value of the crts property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCrts(BigDecimal value) {
            this.crts = value;
        }

        /**
         * Gets the value of the ward property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWard() {
            return ward;
        }

        /**
         * Sets the value of the ward property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWard(String value) {
            this.ward = value;
        }

        /**
         * Gets the value of the postcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostcode() {
            return postcode;
        }

        /**
         * Sets the value of the postcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostcode(String value) {
            this.postcode = value;
        }

    }

}
