//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:03:12 PM GMT 
//


package Sandbox.ZipExtractor;;

import Sandbox.ZipExtractor.*;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gb.informaticasystems.schemas.src.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gb.informaticasystems.schemas.src.generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Geomapping }
     * 
     */
    public Geomapping createGeomapping() {
        return new Geomapping();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Configuration.Licensing }
     * 
     */
    public Configuration.Licensing createConfigurationLicensing() {
        return new Configuration.Licensing();
    }

    /**
     * Create an instance of {@link Configuration.IcapRepositories }
     * 
     */
    public Configuration.IcapRepositories createConfigurationIcapRepositories() {
        return new Configuration.IcapRepositories();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Geomapping.Geodata }
     * 
     */
    public Geomapping.Geodata createGeomappingGeodata() {
        return new Geomapping.Geodata();
    }

    /**
     * Create an instance of {@link Tranche }
     * 
     */
    public Tranche createTranche() {
        return new Tranche();
    }

    /**
     * Create an instance of {@link Ruleset }
     * 
     */
    public Ruleset createRuleset() {
        return new Ruleset();
    }

    /**
     * Create an instance of {@link Practice }
     * 
     */
    public Practice createPractice() {
        return new Practice();
    }

    /**
     * Create an instance of {@link StaticData }
     * 
     */
    public StaticData createStaticData() {
        return new StaticData();
    }

    /**
     * Create an instance of {@link Rulesets }
     * 
     */
    public Rulesets createRulesets() {
        return new Rulesets();
    }

    /**
     * Create an instance of {@link ProductDownloads }
     * 
     */
    public ProductDownloads createProductDownloads() {
        return new ProductDownloads();
    }

    /**
     * Create an instance of {@link Release }
     * 
     */
    public Release createRelease() {
        return new Release();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Registry }
     * 
     */
    public Registry createRegistry() {
        return new Registry();
    }

    /**
     * Create an instance of {@link Sandbox.ZipExtractor.Geodata }
     * 
     */
    public Sandbox.ZipExtractor.Geodata createGeodata() {
        return new Sandbox.ZipExtractor.Geodata();
    }

    /**
     * Create an instance of {@link Configuration.Licensing.Module }
     * 
     */
    public Configuration.Licensing.Module createConfigurationLicensingModule() {
        return new Configuration.Licensing.Module();
    }

    /**
     * Create an instance of {@link Configuration.IcapRepositories.IcapRepository }
     * 
     */
    public Configuration.IcapRepositories.IcapRepository createConfigurationIcapRepositoriesIcapRepository() {
        return new Configuration.IcapRepositories.IcapRepository();
    }

}
