//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:03:12 PM GMT 
//


package Sandbox.ZipExtractor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="national-code" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="country" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="current-version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clinical-system" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clinical-system-version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rulesets" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="list-size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="site-guid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operating-system" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="registered-organisation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="domain" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpu" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="memory" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="installation-date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="last-extraction-date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="last-failed-extraction-date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="last-submission-date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="system-status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="analysis-status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="buffer-status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="appointments-online-subdomain" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="appointments-online-status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clinical-system-configuration" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="support-tool" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="active-user-count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="prescribing-plus-metrics" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "practice")
public class Practice {

    @XmlAttribute(name = "national-code", required = true)
    protected String nationalCode;
    @XmlAttribute(name = "country", required = true)
    protected String country;
    @XmlAttribute(name = "current-version", required = true)
    protected String currentVersion;
    @XmlAttribute(name = "clinical-system", required = true)
    protected String clinicalSystem;
    @XmlAttribute(name = "clinical-system-version", required = true)
    protected String clinicalSystemVersion;
    @XmlAttribute(name = "rulesets", required = true)
    protected String rulesets;
    @XmlAttribute(name = "list-size", required = true)
    protected int listSize;
    @XmlAttribute(name = "site-guid", required = true)
    protected String siteGuid;
    @XmlAttribute(name = "operating-system", required = true)
    protected String operatingSystem;
    @XmlAttribute(name = "registered-organisation", required = true)
    protected String registeredOrganisation;
    @XmlAttribute(name = "domain", required = true)
    protected String domain;
    @XmlAttribute(name = "cpu", required = true)
    protected String cpu;
    @XmlAttribute(name = "memory", required = true)
    protected String memory;
    @XmlAttribute(name = "installation-date", required = true)
    protected String installationDate;
    @XmlAttribute(name = "last-extraction-date", required = true)
    protected String lastExtractionDate;
    @XmlAttribute(name = "last-failed-extraction-date", required = true)
    protected String lastFailedExtractionDate;
    @XmlAttribute(name = "last-submission-date", required = true)
    protected String lastSubmissionDate;
    @XmlAttribute(name = "system-status", required = true)
    protected String systemStatus;
    @XmlAttribute(name = "analysis-status", required = true)
    protected String analysisStatus;
    @XmlAttribute(name = "buffer-status", required = true)
    protected String bufferStatus;
    @XmlAttribute(name = "appointments-online-subdomain", required = true)
    protected String appointmentsOnlineSubdomain;
    @XmlAttribute(name = "appointments-online-status", required = true)
    protected String appointmentsOnlineStatus;
    @XmlAttribute(name = "clinical-system-configuration", required = true)
    protected String clinicalSystemConfiguration;
    @XmlAttribute(name = "support-tool", required = true)
    protected String supportTool;
    @XmlAttribute(name = "active-user-count", required = true)
    protected int activeUserCount;
    @XmlAttribute(name = "prescribing-plus-metrics", required = true)
    protected String prescribingPlusMetrics;

    /**
     * Gets the value of the nationalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalCode() {
        return nationalCode;
    }

    /**
     * Sets the value of the nationalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalCode(String value) {
        this.nationalCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the currentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentVersion() {
        return currentVersion;
    }

    /**
     * Sets the value of the currentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentVersion(String value) {
        this.currentVersion = value;
    }

    /**
     * Gets the value of the clinicalSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalSystem() {
        return clinicalSystem;
    }

    /**
     * Sets the value of the clinicalSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalSystem(String value) {
        this.clinicalSystem = value;
    }

    /**
     * Gets the value of the clinicalSystemVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalSystemVersion() {
        return clinicalSystemVersion;
    }

    /**
     * Sets the value of the clinicalSystemVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalSystemVersion(String value) {
        this.clinicalSystemVersion = value;
    }

    /**
     * Gets the value of the rulesets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRulesets() {
        return rulesets;
    }

    /**
     * Sets the value of the rulesets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRulesets(String value) {
        this.rulesets = value;
    }

    /**
     * Gets the value of the listSize property.
     * 
     */
    public int getListSize() {
        return listSize;
    }

    /**
     * Sets the value of the listSize property.
     * 
     */
    public void setListSize(int value) {
        this.listSize = value;
    }

    /**
     * Gets the value of the siteGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteGuid() {
        return siteGuid;
    }

    /**
     * Sets the value of the siteGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteGuid(String value) {
        this.siteGuid = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingSystem(String value) {
        this.operatingSystem = value;
    }

    /**
     * Gets the value of the registeredOrganisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisteredOrganisation() {
        return registeredOrganisation;
    }

    /**
     * Sets the value of the registeredOrganisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisteredOrganisation(String value) {
        this.registeredOrganisation = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the cpu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpu() {
        return cpu;
    }

    /**
     * Sets the value of the cpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpu(String value) {
        this.cpu = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemory(String value) {
        this.memory = value;
    }

    /**
     * Gets the value of the installationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallationDate() {
        return installationDate;
    }

    /**
     * Sets the value of the installationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallationDate(String value) {
        this.installationDate = value;
    }

    /**
     * Gets the value of the lastExtractionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastExtractionDate() {
        return lastExtractionDate;
    }

    /**
     * Sets the value of the lastExtractionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastExtractionDate(String value) {
        this.lastExtractionDate = value;
    }

    /**
     * Gets the value of the lastFailedExtractionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastFailedExtractionDate() {
        return lastFailedExtractionDate;
    }

    /**
     * Sets the value of the lastFailedExtractionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastFailedExtractionDate(String value) {
        this.lastFailedExtractionDate = value;
    }

    /**
     * Gets the value of the lastSubmissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastSubmissionDate() {
        return lastSubmissionDate;
    }

    /**
     * Sets the value of the lastSubmissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastSubmissionDate(String value) {
        this.lastSubmissionDate = value;
    }

    /**
     * Gets the value of the systemStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemStatus() {
        return systemStatus;
    }

    /**
     * Sets the value of the systemStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemStatus(String value) {
        this.systemStatus = value;
    }

    /**
     * Gets the value of the analysisStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisStatus() {
        return analysisStatus;
    }

    /**
     * Sets the value of the analysisStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisStatus(String value) {
        this.analysisStatus = value;
    }

    /**
     * Gets the value of the bufferStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferStatus() {
        return bufferStatus;
    }

    /**
     * Sets the value of the bufferStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferStatus(String value) {
        this.bufferStatus = value;
    }

    /**
     * Gets the value of the appointmentsOnlineSubdomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointmentsOnlineSubdomain() {
        return appointmentsOnlineSubdomain;
    }

    /**
     * Sets the value of the appointmentsOnlineSubdomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointmentsOnlineSubdomain(String value) {
        this.appointmentsOnlineSubdomain = value;
    }

    /**
     * Gets the value of the appointmentsOnlineStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppointmentsOnlineStatus() {
        return appointmentsOnlineStatus;
    }

    /**
     * Sets the value of the appointmentsOnlineStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppointmentsOnlineStatus(String value) {
        this.appointmentsOnlineStatus = value;
    }

    /**
     * Gets the value of the clinicalSystemConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicalSystemConfiguration() {
        return clinicalSystemConfiguration;
    }

    /**
     * Sets the value of the clinicalSystemConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicalSystemConfiguration(String value) {
        this.clinicalSystemConfiguration = value;
    }

    /**
     * Gets the value of the supportTool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupportTool() {
        return supportTool;
    }

    /**
     * Sets the value of the supportTool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupportTool(String value) {
        this.supportTool = value;
    }

    /**
     * Gets the value of the activeUserCount property.
     * 
     */
    public int getActiveUserCount() {
        return activeUserCount;
    }

    /**
     * Sets the value of the activeUserCount property.
     * 
     */
    public void setActiveUserCount(int value) {
        this.activeUserCount = value;
    }

    /**
     * Gets the value of the prescribingPlusMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescribingPlusMetrics() {
        return prescribingPlusMetrics;
    }

    /**
     * Sets the value of the prescribingPlusMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescribingPlusMetrics(String value) {
        this.prescribingPlusMetrics = value;
    }

}
