//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:03:12 PM GMT 
//


package Sandbox.ZipExtractor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rulesets"/>
 *         &lt;element ref="{}product-downloads"/>
 *         &lt;element ref="{}options"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rulesets",
    "productDownloads",
    "options"
})
@XmlRootElement(name = "static-data")
public class StaticData {

    @XmlElement(required = true)
    protected Rulesets rulesets;
    @XmlElement(name = "product-downloads", required = true)
    protected ProductDownloads productDownloads;
    @XmlElement(required = true)
    protected Options options;

    /**
     * Gets the value of the rulesets property.
     * 
     * @return
     *     possible object is
     *     {@link Rulesets }
     *     
     */
    public Rulesets getRulesets() {
        return rulesets;
    }

    /**
     * Sets the value of the rulesets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rulesets }
     *     
     */
    public void setRulesets(Rulesets value) {
        this.rulesets = value;
    }

    /**
     * Gets the value of the productDownloads property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDownloads }
     *     
     */
    public ProductDownloads getProductDownloads() {
        return productDownloads;
    }

    /**
     * Sets the value of the productDownloads property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDownloads }
     *     
     */
    public void setProductDownloads(ProductDownloads value) {
        this.productDownloads = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Options }
     *     
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options }
     *     
     */
    public void setOptions(Options value) {
        this.options = value;
    }

}
